/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef PROJECTFOTOGAMETRIA_PRIVATE_H
#define PROJECTFOTOGAMETRIA_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.0.0.0"
#define VER_MAJOR	1
#define VER_MINOR	0
#define VER_RELEASE	0
#define VER_BUILD	0
#define COMPANY_NAME	"FCT UNESP - PRESIDENTE PRUDENTE"
#define FILE_VERSION	"1.0.0.0"
#define FILE_DESCRIPTION	"Developed using the Dev-C++ IDE"
#define INTERNAL_NAME	"Gustavo Serpeloni"
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	"PROJETO FOTOGAMETRIA"
#define PRODUCT_NAME	""
#define PRODUCT_VERSION	"1.0.0.0"

#endif /*PROJECTFOTOGAMETRIA_PRIVATE_H*/
